wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Selfmade
epochs:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723037242
    t:
      1:
      - 2
      - 3
      - 5
      - 15
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 15
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
